spring.application.name=ia.service

spring.config.import=optional:file:./.env[.properties]

spring.jpa.hibernate.ddl-auto=validate

spring.data.redis.url=${REDIS_URL}
spring.data.mongodb.uri=${MONGO_URL}

jwt.secret=${SECRET}
jwt.issuer=${ISSUER}
jwt.audience=${AUDIENCE}

spring.ai.google.genai.api-key=${GERMINI_API_KEY}
spring.ai.google.genai.chat.options.model=${GERMINI_MODEL}

extract.hardskills.prompt=${EXTRACT_HARDSKILLS_PROMPT}