spring.application.name=ia.service

spring.config.import=optional:file:./.env[.properties]

management.health.mongodb.enabled=false

spring.jpa.hibernate.ddl-auto=none

debug=true

spring.data.redis.url=${REDIS_URL}
spring.mongodb.uri=${MONGO_URL}
spring.mongodb.database=${MONGO_DATABASE_NAME}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${SECRET}
jwt.internal.secret=${INTERNAL_SECRET}
jwt.issuer=${ISSUER}
jwt.audience=${AUDIENCE}

spring.ai.google.genai.api-key=${GERMINI_API_KEY}
spring.ai.google.genai.chat.model=${GERMINI_MODEL}

extract.hardskills.prompt.file=${EXTRACT_HARDSKILLS_PROMPT_FILE}
get.softskills.prompt.file=${GET_SOFTSKILLS_PROMPT_FILE}